const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const SRC_DIR = path.join(__dirname);
const DIST_DIR = path.join(__dirname, 'dist');
const PUBLIC_DIR = path.join(__dirname, 'public');

const STATIC_FILES = ['config.js', 'grid.js', 'pixels.js', 'map.js', 'app.js'];

function hashFile(filepath) {
  const content = fs.readFileSync(filepath);
  return crypto.createHash('md5').update(content).digest('hex').slice(0, 8);
}

function copyWithHash(srcFile, destDir, suffix = '') {
  const ext = path.extname(srcFile);
  const base = path.basename(srcFile, ext);
  const hash = hashFile(srcFile);
  const newName = `${base}.${hash}${suffix || ext}`;
  
  fs.copyFileSync(srcFile, path.join(destDir, newName));
  return newName;
}

// Clean dist/
if (fs.existsSync(DIST_DIR)) {
  fs.rmSync(DIST_DIR, { recursive: true, force: true });
}
fs.mkdirSync(DIST_DIR);

console.log('Building Pixhood frontend...');

// Hash and copy static JS files
const hashedJsFiles = {};
const jsFiles = ['config.js', 'grid.js', 'pixels.js', 'map.js', 'app.js'];
jsFiles.forEach(file => {
  const hashedName = copyWithHash(path.join(SRC_DIR, file), DIST_DIR);
  hashedJsFiles[file] = hashedName;
  console.log(`  ${file} → ${hashedName}`);
});

// Hash and copy CSS
const cssHash = hashFile(path.join(SRC_DIR, 'style.css'));
const hashedCssName = `style.${cssHash}.css`;
fs.copyFileSync(
  path.join(SRC_DIR, 'style.css'),
  path.join(DIST_DIR, hashedCssName)
);
console.log(`  style.css → ${hashedCssName}`);

// Rewrite index.html with hashed filenames
let html = fs.readFileSync(path.join(SRC_DIR, 'index.html'), 'utf8');
html = html.replace('style.css', hashedCssName);
Object.entries(hashedJsFiles).forEach(([orig, hashed]) => {
  html = html.replace(new RegExp(orig.replace('.', '\\.'), 'g'), hashed);
});

fs.writeFileSync(path.join(DIST_DIR, 'index.html'), html);
console.log('  index.html (rewritten)');

// Copy favicon.svg
fs.copyFileSync(
  path.join(SRC_DIR, 'favicon.svg'),
  path.join(DIST_DIR, 'favicon.svg')
);
console.log('  favicon.svg');

// Copy public/ contents (icons, manifest, headers)
if (fs.existsSync(PUBLIC_DIR)) {
  const publicFiles = fs.readdirSync(PUBLIC_DIR);
  publicFiles.forEach(file => {
    const src = path.join(PUBLIC_DIR, file);
    const dest = path.join(DIST_DIR, file);
    if (fs.statSync(src).isFile()) {
      fs.copyFileSync(src, dest);
      console.log(`  ${file}`);
    }
  });
}

// Generate service worker with precache manifest
const precacheList = [
  '/',
  '/index.html',
  `/${hashedCssName}`,
  ...Object.values(hashedJsFiles).map(f => `/${f}`),
  '/favicon.svg',
  '/manifest.json',
  '/icon-192.png',
  '/icon-512.png'
];

const swContent = `// Auto-generated by build.js
const CACHE_NAME = 'pixhood-v1';
const PRECACHE_ASSETS = ${JSON.stringify(precacheList, null, 2)};

const DEV_MODE = self.location.hostname === 'localhost';

self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE_NAME).then(cache => {
      return cache.addAll(PRECACHE_ASSETS);
    })
  );
  self.skipWaiting();
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys().then(cacheNames => {
      return Promise.all(
        cacheNames
          .filter(name => name !== CACHE_NAME)
          .map(name => caches.delete(name))
      );
    })
  );
  self.clients.claim();
});

self.addEventListener('fetch', event => {
  if (DEV_MODE) {
    return;
  }

  const url = new URL(event.request.url);

  // Cache API only supports http(s) GET requests
  if (event.request.method !== 'GET') {
    return;
  }

  if (url.protocol !== 'http:' && url.protocol !== 'https:') {
    return;
  }

  // Skip service worker itself
  if (url.pathname === '/sw.js') {
    return;
  }
  
  // Network-first for API calls
  if (url.pathname.startsWith('/pixels') || url.pathname.startsWith('/ws')) {
    event.respondWith(
      fetch(event.request)
        .catch(() => new Response(JSON.stringify({ error: 'offline' }), {
          headers: { 'Content-Type': 'application/json' }
        }))
    );
    return;
  }

  // Cache-first for static assets
  event.respondWith(
    caches.match(event.request).then(cached => {
      if (cached) {
// Return cached, update in background
      fetch(event.request).then(response => {
        if (response.ok) {
          caches.open(CACHE_NAME).then(cache => {
            cache.put(event.request, response);
          });
        }
      }).catch(() => {});
      return cached;
      }
      
      return fetch(event.request).then(response => {
        if (response.ok) {
          const clone = response.clone();
          caches.open(CACHE_NAME).then(cache => {
            cache.put(event.request, clone);
          });
        }
        return response;
      }).catch(() => {
        // Ignore fetch errors for offline fallbacks
      });
    })
  );
});
`;

fs.writeFileSync(path.join(DIST_DIR, 'sw.js'), swContent);
console.log('  sw.js (generated)');

console.log('Build complete! Output in dist/');
